package main

import (
	"bytes"
	"fmt"
	"os"
	"strconv"

	"github.com/denysvitali/transit-planner/router/catalog"
)

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Generated by `go run ./tool/generate_feed_catalog`; do not edit by hand.\n")
	buf.WriteString("part of 'feed_catalog.dart';\n\n")
	buf.WriteString("const List<TransitFeed> kTransitFeeds = [\n")
	for _, network := range catalog.Networks {
		writeNetwork(&buf, network)
	}
	for _, feed := range catalog.SortedFeeds() {
		writeFeed(&buf, feed)
	}
	buf.WriteString("];\n")

	if err := os.WriteFile("lib/src/feed_catalog.g.dart", buf.Bytes(), 0o644); err != nil {
		panic(err)
	}
}

func writeNetwork(buf *bytes.Buffer, network catalog.NetworkSpec) {
	buf.WriteString("  TransitFeed(\n")
	writeCommon(buf, network.ID, network.Name, network.Description, network.Country, network.Region, network.Publisher, network.License, network.SourceURL, "", network.Attribution, network.CenterLatitude, network.CenterLongitude, network.DefaultDepartureHour, "")
	writeStringList(buf, "componentFeedIds", network.ComponentFeedIDs)
	buf.WriteString("  ),\n")
}

func writeFeed(buf *bytes.Buffer, feed catalog.FeedSpec) {
	buf.WriteString("  TransitFeed(\n")
	writeCommon(buf, feed.ID, feed.Name, feed.Description, feed.Country, feed.Region, feed.Publisher, feed.License, feed.SourceURL, feed.LocalFileName, feed.Attribution, feed.CenterLatitude, feed.CenterLongitude, feed.DefaultDepartureHour, feed.BundledAssetPath)
	buf.WriteString("  ),\n")
}

func writeCommon(buf *bytes.Buffer, id, name, description, country, region, publisher, license, sourceURL, localFileName, attribution string, lat, lon float64, hour *int, bundled string) {
	writeString(buf, "id", id)
	writeString(buf, "name", name)
	writeString(buf, "description", description)
	writeString(buf, "country", country)
	writeString(buf, "region", region)
	writeString(buf, "publisher", publisher)
	writeString(buf, "license", license)
	writeString(buf, "sourceUrl", sourceURL)
	writeString(buf, "localFileName", localFileName)
	writeString(buf, "attribution", attribution)
	if bundled != "" {
		writeString(buf, "bundledAssetPath", bundled)
	}
	if hour != nil {
		fmt.Fprintf(buf, "    defaultDepartureHour: %d,\n", *hour)
	}
	fmt.Fprintf(buf, "    centerLatitude: %s,\n", strconv.FormatFloat(lat, 'f', -1, 64))
	fmt.Fprintf(buf, "    centerLongitude: %s,\n", strconv.FormatFloat(lon, 'f', -1, 64))
}

func writeString(buf *bytes.Buffer, key, value string) {
	fmt.Fprintf(buf, "    %s: %q,\n", key, value)
}

func writeStringList(buf *bytes.Buffer, key string, values []string) {
	fmt.Fprintf(buf, "    %s: [\n", key)
	for _, value := range values {
		fmt.Fprintf(buf, "      %q,\n", value)
	}
	buf.WriteString("    ],\n")
}
