// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ActiveAgency struct {
	FeedID         int64          `json:"feed_id"`
	FeedVersionID  int64          `json:"feed_version_id"`
	AgencyID       string         `json:"agency_id"`
	AgencyName     sql.NullString `json:"agency_name"`
	AgencyUrl      sql.NullString `json:"agency_url"`
	AgencyTimezone sql.NullString `json:"agency_timezone"`
	AgencyLang     sql.NullString `json:"agency_lang"`
	AgencyPhone    sql.NullString `json:"agency_phone"`
	AgencyFareUrl  sql.NullString `json:"agency_fare_url"`
	AgencyEmail    sql.NullString `json:"agency_email"`
}

type ActiveCalendar struct {
	FeedID        int64          `json:"feed_id"`
	FeedVersionID int64          `json:"feed_version_id"`
	ServiceID     string         `json:"service_id"`
	Monday        sql.NullInt64  `json:"monday"`
	Tuesday       sql.NullInt64  `json:"tuesday"`
	Wednesday     sql.NullInt64  `json:"wednesday"`
	Thursday      sql.NullInt64  `json:"thursday"`
	Friday        sql.NullInt64  `json:"friday"`
	Saturday      sql.NullInt64  `json:"saturday"`
	Sunday        sql.NullInt64  `json:"sunday"`
	StartDate     sql.NullString `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
}

type ActiveCalendarDate struct {
	FeedID        int64         `json:"feed_id"`
	FeedVersionID int64         `json:"feed_version_id"`
	ServiceID     string        `json:"service_id"`
	Date          string        `json:"date"`
	ExceptionType sql.NullInt64 `json:"exception_type"`
}

type ActiveFeedInfo struct {
	FeedID            int64          `json:"feed_id"`
	FeedVersionID     int64          `json:"feed_version_id"`
	FeedPublisherName sql.NullString `json:"feed_publisher_name"`
	FeedPublisherUrl  sql.NullString `json:"feed_publisher_url"`
	FeedLang          sql.NullString `json:"feed_lang"`
	DefaultLang       sql.NullString `json:"default_lang"`
	FeedStartDate     sql.NullString `json:"feed_start_date"`
	FeedEndDate       sql.NullString `json:"feed_end_date"`
	FeedVersion       sql.NullString `json:"feed_version"`
	FeedContactEmail  sql.NullString `json:"feed_contact_email"`
}

type ActiveRoute struct {
	FeedID           int64          `json:"feed_id"`
	FeedVersionID    int64          `json:"feed_version_id"`
	RouteID          string         `json:"route_id"`
	AgencyID         sql.NullString `json:"agency_id"`
	RouteShortName   sql.NullString `json:"route_short_name"`
	RouteLongName    sql.NullString `json:"route_long_name"`
	RouteDesc        sql.NullString `json:"route_desc"`
	RouteType        sql.NullInt64  `json:"route_type"`
	RouteUrl         sql.NullString `json:"route_url"`
	RouteColor       sql.NullString `json:"route_color"`
	RouteTextColor   sql.NullString `json:"route_text_color"`
	RouteSortOrder   sql.NullString `json:"route_sort_order"`
	ContinuousPickup sql.NullString `json:"continuous_pickup"`
}

type ActiveShape struct {
	FeedID          int64           `json:"feed_id"`
	FeedVersionID   int64           `json:"feed_version_id"`
	ShapeID         string          `json:"shape_id"`
	ShapePtLat      sql.NullFloat64 `json:"shape_pt_lat"`
	ShapePtLon      sql.NullFloat64 `json:"shape_pt_lon"`
	ShapePtSequence sql.NullInt64   `json:"shape_pt_sequence"`
}

type ActiveStop struct {
	FeedID             int64           `json:"feed_id"`
	FeedVersionID      int64           `json:"feed_version_id"`
	StopID             string          `json:"stop_id"`
	StopCode           sql.NullString  `json:"stop_code"`
	StopName           sql.NullString  `json:"stop_name"`
	StopDesc           sql.NullString  `json:"stop_desc"`
	StopLat            sql.NullFloat64 `json:"stop_lat"`
	StopLon            sql.NullFloat64 `json:"stop_lon"`
	ZoneID             sql.NullString  `json:"zone_id"`
	StopUrl            sql.NullString  `json:"stop_url"`
	LocationType       sql.NullInt64   `json:"location_type"`
	ParentStation      sql.NullString  `json:"parent_station"`
	StopTimezone       sql.NullString  `json:"stop_timezone"`
	WheelchairBoarding sql.NullString  `json:"wheelchair_boarding"`
	PlatformCode       sql.NullString  `json:"platform_code"`
}

type ActiveStopTime struct {
	FeedID            int64           `json:"feed_id"`
	FeedVersionID     int64           `json:"feed_version_id"`
	RowIndex          int64           `json:"row_index"`
	TripID            string          `json:"trip_id"`
	ArrivalTime       sql.NullString  `json:"arrival_time"`
	DepartureTime     sql.NullString  `json:"departure_time"`
	StopID            string          `json:"stop_id"`
	StopSequence      sql.NullInt64   `json:"stop_sequence"`
	StopHeadsign      sql.NullString  `json:"stop_headsign"`
	PickupType        sql.NullString  `json:"pickup_type"`
	DropOffType       sql.NullString  `json:"drop_off_type"`
	ContinuousPickup  sql.NullString  `json:"continuous_pickup"`
	ContinuousDropOff sql.NullString  `json:"continuous_drop_off"`
	ShapeDistTraveled sql.NullFloat64 `json:"shape_dist_traveled"`
	Timepoint         sql.NullString  `json:"timepoint"`
}

type ActiveTransfer struct {
	FeedID          int64          `json:"feed_id"`
	FeedVersionID   int64          `json:"feed_version_id"`
	FromStopID      sql.NullString `json:"from_stop_id"`
	ToStopID        sql.NullString `json:"to_stop_id"`
	FromRouteID     sql.NullString `json:"from_route_id"`
	ToRouteID       sql.NullString `json:"to_route_id"`
	FromTripID      sql.NullString `json:"from_trip_id"`
	ToTripID        sql.NullString `json:"to_trip_id"`
	TransferType    sql.NullInt64  `json:"transfer_type"`
	MinTransferTime sql.NullInt64  `json:"min_transfer_time"`
}

type ActiveTrip struct {
	FeedID               int64          `json:"feed_id"`
	FeedVersionID        int64          `json:"feed_version_id"`
	RouteID              string         `json:"route_id"`
	ServiceID            string         `json:"service_id"`
	TripID               string         `json:"trip_id"`
	TripHeadsign         sql.NullString `json:"trip_headsign"`
	TripShortName        sql.NullString `json:"trip_short_name"`
	DirectionID          sql.NullInt64  `json:"direction_id"`
	BlockID              sql.NullString `json:"block_id"`
	ShapeID              sql.NullString `json:"shape_id"`
	WheelchairAccessible sql.NullString `json:"wheelchair_accessible"`
	BikesAllowed         sql.NullString `json:"bikes_allowed"`
	CarsAllowed          sql.NullString `json:"cars_allowed"`
}

type Agency struct {
	FeedID         int64          `json:"feed_id"`
	FeedVersionID  int64          `json:"feed_version_id"`
	AgencyID       string         `json:"agency_id"`
	AgencyName     sql.NullString `json:"agency_name"`
	AgencyUrl      sql.NullString `json:"agency_url"`
	AgencyTimezone sql.NullString `json:"agency_timezone"`
	AgencyLang     sql.NullString `json:"agency_lang"`
	AgencyPhone    sql.NullString `json:"agency_phone"`
	AgencyFareUrl  sql.NullString `json:"agency_fare_url"`
	AgencyEmail    sql.NullString `json:"agency_email"`
}

type Calendar struct {
	FeedID        int64          `json:"feed_id"`
	FeedVersionID int64          `json:"feed_version_id"`
	ServiceID     string         `json:"service_id"`
	Monday        sql.NullInt64  `json:"monday"`
	Tuesday       sql.NullInt64  `json:"tuesday"`
	Wednesday     sql.NullInt64  `json:"wednesday"`
	Thursday      sql.NullInt64  `json:"thursday"`
	Friday        sql.NullInt64  `json:"friday"`
	Saturday      sql.NullInt64  `json:"saturday"`
	Sunday        sql.NullInt64  `json:"sunday"`
	StartDate     sql.NullString `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
}

type CalendarDate struct {
	FeedID        int64         `json:"feed_id"`
	FeedVersionID int64         `json:"feed_version_id"`
	ServiceID     string        `json:"service_id"`
	Date          string        `json:"date"`
	ExceptionType sql.NullInt64 `json:"exception_type"`
}

type Feed struct {
	ID              int64          `json:"id"`
	Code            string         `json:"code"`
	Name            string         `json:"name"`
	CountryCode     sql.NullString `json:"country_code"`
	Region          sql.NullString `json:"region"`
	PublisherName   sql.NullString `json:"publisher_name"`
	LicenseName     sql.NullString `json:"license_name"`
	SourceUrl       sql.NullString `json:"source_url"`
	AttributionText sql.NullString `json:"attribution_text"`
	CreatedAt       string         `json:"created_at"`
}

type FeedInfo struct {
	FeedID            int64          `json:"feed_id"`
	FeedVersionID     int64          `json:"feed_version_id"`
	FeedPublisherName sql.NullString `json:"feed_publisher_name"`
	FeedPublisherUrl  sql.NullString `json:"feed_publisher_url"`
	FeedLang          sql.NullString `json:"feed_lang"`
	DefaultLang       sql.NullString `json:"default_lang"`
	FeedStartDate     sql.NullString `json:"feed_start_date"`
	FeedEndDate       sql.NullString `json:"feed_end_date"`
	FeedVersion       sql.NullString `json:"feed_version"`
	FeedContactEmail  sql.NullString `json:"feed_contact_email"`
}

type FeedVersion struct {
	ID         int64          `json:"id"`
	FeedID     int64          `json:"feed_id"`
	SourcePath string         `json:"source_path"`
	SourceUrl  sql.NullString `json:"source_url"`
	Sha256     string         `json:"sha256"`
	ImportedAt string         `json:"imported_at"`
	Active     int64          `json:"active"`
}

type GtfsFile struct {
	ID            int64  `json:"id"`
	FeedID        int64  `json:"feed_id"`
	FeedVersionID int64  `json:"feed_version_id"`
	Filename      string `json:"filename"`
	Sha256        string `json:"sha256"`
	HeaderJson    string `json:"header_json"`
	RowCount      int64  `json:"row_count"`
	RawCsv        []byte `json:"raw_csv"`
}

type GtfsRow struct {
	ID            int64  `json:"id"`
	FeedID        int64  `json:"feed_id"`
	FeedVersionID int64  `json:"feed_version_id"`
	FileID        int64  `json:"file_id"`
	Filename      string `json:"filename"`
	RowIndex      int64  `json:"row_index"`
	RowJson       string `json:"row_json"`
}

type Route struct {
	FeedID           int64          `json:"feed_id"`
	FeedVersionID    int64          `json:"feed_version_id"`
	RouteID          string         `json:"route_id"`
	AgencyID         sql.NullString `json:"agency_id"`
	RouteShortName   sql.NullString `json:"route_short_name"`
	RouteLongName    sql.NullString `json:"route_long_name"`
	RouteDesc        sql.NullString `json:"route_desc"`
	RouteType        sql.NullInt64  `json:"route_type"`
	RouteUrl         sql.NullString `json:"route_url"`
	RouteColor       sql.NullString `json:"route_color"`
	RouteTextColor   sql.NullString `json:"route_text_color"`
	RouteSortOrder   sql.NullString `json:"route_sort_order"`
	ContinuousPickup sql.NullString `json:"continuous_pickup"`
}

type Shape struct {
	FeedID          int64           `json:"feed_id"`
	FeedVersionID   int64           `json:"feed_version_id"`
	ShapeID         string          `json:"shape_id"`
	ShapePtLat      sql.NullFloat64 `json:"shape_pt_lat"`
	ShapePtLon      sql.NullFloat64 `json:"shape_pt_lon"`
	ShapePtSequence sql.NullInt64   `json:"shape_pt_sequence"`
}

type Stop struct {
	FeedID             int64           `json:"feed_id"`
	FeedVersionID      int64           `json:"feed_version_id"`
	StopID             string          `json:"stop_id"`
	StopCode           sql.NullString  `json:"stop_code"`
	StopName           sql.NullString  `json:"stop_name"`
	StopDesc           sql.NullString  `json:"stop_desc"`
	StopLat            sql.NullFloat64 `json:"stop_lat"`
	StopLon            sql.NullFloat64 `json:"stop_lon"`
	ZoneID             sql.NullString  `json:"zone_id"`
	StopUrl            sql.NullString  `json:"stop_url"`
	LocationType       sql.NullInt64   `json:"location_type"`
	ParentStation      sql.NullString  `json:"parent_station"`
	StopTimezone       sql.NullString  `json:"stop_timezone"`
	WheelchairBoarding sql.NullString  `json:"wheelchair_boarding"`
	PlatformCode       sql.NullString  `json:"platform_code"`
}

type StopTime struct {
	FeedID            int64           `json:"feed_id"`
	FeedVersionID     int64           `json:"feed_version_id"`
	RowIndex          int64           `json:"row_index"`
	TripID            string          `json:"trip_id"`
	ArrivalTime       sql.NullString  `json:"arrival_time"`
	DepartureTime     sql.NullString  `json:"departure_time"`
	StopID            string          `json:"stop_id"`
	StopSequence      sql.NullInt64   `json:"stop_sequence"`
	StopHeadsign      sql.NullString  `json:"stop_headsign"`
	PickupType        sql.NullString  `json:"pickup_type"`
	DropOffType       sql.NullString  `json:"drop_off_type"`
	ContinuousPickup  sql.NullString  `json:"continuous_pickup"`
	ContinuousDropOff sql.NullString  `json:"continuous_drop_off"`
	ShapeDistTraveled sql.NullFloat64 `json:"shape_dist_traveled"`
	Timepoint         sql.NullString  `json:"timepoint"`
}

type Transfer struct {
	FeedID          int64          `json:"feed_id"`
	FeedVersionID   int64          `json:"feed_version_id"`
	FromStopID      sql.NullString `json:"from_stop_id"`
	ToStopID        sql.NullString `json:"to_stop_id"`
	FromRouteID     sql.NullString `json:"from_route_id"`
	ToRouteID       sql.NullString `json:"to_route_id"`
	FromTripID      sql.NullString `json:"from_trip_id"`
	ToTripID        sql.NullString `json:"to_trip_id"`
	TransferType    sql.NullInt64  `json:"transfer_type"`
	MinTransferTime sql.NullInt64  `json:"min_transfer_time"`
}

type Trip struct {
	FeedID               int64          `json:"feed_id"`
	FeedVersionID        int64          `json:"feed_version_id"`
	RouteID              string         `json:"route_id"`
	ServiceID            string         `json:"service_id"`
	TripID               string         `json:"trip_id"`
	TripHeadsign         sql.NullString `json:"trip_headsign"`
	TripShortName        sql.NullString `json:"trip_short_name"`
	DirectionID          sql.NullInt64  `json:"direction_id"`
	BlockID              sql.NullString `json:"block_id"`
	ShapeID              sql.NullString `json:"shape_id"`
	WheelchairAccessible sql.NullString `json:"wheelchair_accessible"`
	BikesAllowed         sql.NullString `json:"bikes_allowed"`
	CarsAllowed          sql.NullString `json:"cars_allowed"`
}
