// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const deactivateFeedVersions = `-- name: DeactivateFeedVersions :exec
update feed_versions set active = 0 where feed_id = ?
`

func (q *Queries) DeactivateFeedVersions(ctx context.Context, feedID int64) error {
	_, err := q.db.ExecContext(ctx, deactivateFeedVersions, feedID)
	return err
}

const getFeedIDByCode = `-- name: GetFeedIDByCode :one
select id from feeds where code = ?
`

func (q *Queries) GetFeedIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAgency = `-- name: InsertAgency :exec
insert into agencies (
	feed_id, feed_version_id, agency_id, agency_name, agency_url, agency_timezone,
	agency_lang, agency_phone, agency_fare_url, agency_email
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAgencyParams struct {
	FeedID         int64          `json:"feed_id"`
	FeedVersionID  int64          `json:"feed_version_id"`
	AgencyID       string         `json:"agency_id"`
	AgencyName     sql.NullString `json:"agency_name"`
	AgencyUrl      sql.NullString `json:"agency_url"`
	AgencyTimezone sql.NullString `json:"agency_timezone"`
	AgencyLang     sql.NullString `json:"agency_lang"`
	AgencyPhone    sql.NullString `json:"agency_phone"`
	AgencyFareUrl  sql.NullString `json:"agency_fare_url"`
	AgencyEmail    sql.NullString `json:"agency_email"`
}

func (q *Queries) InsertAgency(ctx context.Context, arg InsertAgencyParams) error {
	_, err := q.db.ExecContext(ctx, insertAgency,
		arg.FeedID,
		arg.FeedVersionID,
		arg.AgencyID,
		arg.AgencyName,
		arg.AgencyUrl,
		arg.AgencyTimezone,
		arg.AgencyLang,
		arg.AgencyPhone,
		arg.AgencyFareUrl,
		arg.AgencyEmail,
	)
	return err
}

const insertCalendar = `-- name: InsertCalendar :exec
insert into calendars (
	feed_id, feed_version_id, service_id, monday, tuesday, wednesday, thursday,
	friday, saturday, sunday, start_date, end_date
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertCalendarParams struct {
	FeedID        int64          `json:"feed_id"`
	FeedVersionID int64          `json:"feed_version_id"`
	ServiceID     string         `json:"service_id"`
	Monday        sql.NullInt64  `json:"monday"`
	Tuesday       sql.NullInt64  `json:"tuesday"`
	Wednesday     sql.NullInt64  `json:"wednesday"`
	Thursday      sql.NullInt64  `json:"thursday"`
	Friday        sql.NullInt64  `json:"friday"`
	Saturday      sql.NullInt64  `json:"saturday"`
	Sunday        sql.NullInt64  `json:"sunday"`
	StartDate     sql.NullString `json:"start_date"`
	EndDate       sql.NullString `json:"end_date"`
}

func (q *Queries) InsertCalendar(ctx context.Context, arg InsertCalendarParams) error {
	_, err := q.db.ExecContext(ctx, insertCalendar,
		arg.FeedID,
		arg.FeedVersionID,
		arg.ServiceID,
		arg.Monday,
		arg.Tuesday,
		arg.Wednesday,
		arg.Thursday,
		arg.Friday,
		arg.Saturday,
		arg.Sunday,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const insertCalendarDate = `-- name: InsertCalendarDate :exec
insert into calendar_dates (
	feed_id, feed_version_id, service_id, date, exception_type
) values (?, ?, ?, ?, ?)
`

type InsertCalendarDateParams struct {
	FeedID        int64         `json:"feed_id"`
	FeedVersionID int64         `json:"feed_version_id"`
	ServiceID     string        `json:"service_id"`
	Date          string        `json:"date"`
	ExceptionType sql.NullInt64 `json:"exception_type"`
}

func (q *Queries) InsertCalendarDate(ctx context.Context, arg InsertCalendarDateParams) error {
	_, err := q.db.ExecContext(ctx, insertCalendarDate,
		arg.FeedID,
		arg.FeedVersionID,
		arg.ServiceID,
		arg.Date,
		arg.ExceptionType,
	)
	return err
}

const insertFeedInfo = `-- name: InsertFeedInfo :exec
insert into feed_info (
	feed_id, feed_version_id, feed_publisher_name, feed_publisher_url, feed_lang,
	default_lang, feed_start_date, feed_end_date, feed_version, feed_contact_email
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFeedInfoParams struct {
	FeedID            int64          `json:"feed_id"`
	FeedVersionID     int64          `json:"feed_version_id"`
	FeedPublisherName sql.NullString `json:"feed_publisher_name"`
	FeedPublisherUrl  sql.NullString `json:"feed_publisher_url"`
	FeedLang          sql.NullString `json:"feed_lang"`
	DefaultLang       sql.NullString `json:"default_lang"`
	FeedStartDate     sql.NullString `json:"feed_start_date"`
	FeedEndDate       sql.NullString `json:"feed_end_date"`
	FeedVersion       sql.NullString `json:"feed_version"`
	FeedContactEmail  sql.NullString `json:"feed_contact_email"`
}

func (q *Queries) InsertFeedInfo(ctx context.Context, arg InsertFeedInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertFeedInfo,
		arg.FeedID,
		arg.FeedVersionID,
		arg.FeedPublisherName,
		arg.FeedPublisherUrl,
		arg.FeedLang,
		arg.DefaultLang,
		arg.FeedStartDate,
		arg.FeedEndDate,
		arg.FeedVersion,
		arg.FeedContactEmail,
	)
	return err
}

const insertFeedVersion = `-- name: InsertFeedVersion :execresult
insert into feed_versions (
	feed_id, source_path, source_url, sha256, imported_at, active
) values (?, ?, ?, ?, ?, 1)
`

type InsertFeedVersionParams struct {
	FeedID     int64          `json:"feed_id"`
	SourcePath string         `json:"source_path"`
	SourceUrl  sql.NullString `json:"source_url"`
	Sha256     string         `json:"sha256"`
	ImportedAt string         `json:"imported_at"`
}

func (q *Queries) InsertFeedVersion(ctx context.Context, arg InsertFeedVersionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertFeedVersion,
		arg.FeedID,
		arg.SourcePath,
		arg.SourceUrl,
		arg.Sha256,
		arg.ImportedAt,
	)
}

const insertGTFSFile = `-- name: InsertGTFSFile :execresult
insert into gtfs_files (
	feed_id, feed_version_id, filename, sha256, header_json, raw_csv
) values (?, ?, ?, ?, ?, ?)
`

type InsertGTFSFileParams struct {
	FeedID        int64  `json:"feed_id"`
	FeedVersionID int64  `json:"feed_version_id"`
	Filename      string `json:"filename"`
	Sha256        string `json:"sha256"`
	HeaderJson    string `json:"header_json"`
	RawCsv        []byte `json:"raw_csv"`
}

func (q *Queries) InsertGTFSFile(ctx context.Context, arg InsertGTFSFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertGTFSFile,
		arg.FeedID,
		arg.FeedVersionID,
		arg.Filename,
		arg.Sha256,
		arg.HeaderJson,
		arg.RawCsv,
	)
}

const insertGTFSRow = `-- name: InsertGTFSRow :exec
insert into gtfs_rows (
	feed_id, feed_version_id, file_id, filename, row_index, row_json
) values (?, ?, ?, ?, ?, ?)
`

type InsertGTFSRowParams struct {
	FeedID        int64  `json:"feed_id"`
	FeedVersionID int64  `json:"feed_version_id"`
	FileID        int64  `json:"file_id"`
	Filename      string `json:"filename"`
	RowIndex      int64  `json:"row_index"`
	RowJson       string `json:"row_json"`
}

func (q *Queries) InsertGTFSRow(ctx context.Context, arg InsertGTFSRowParams) error {
	_, err := q.db.ExecContext(ctx, insertGTFSRow,
		arg.FeedID,
		arg.FeedVersionID,
		arg.FileID,
		arg.Filename,
		arg.RowIndex,
		arg.RowJson,
	)
	return err
}

const insertRoute = `-- name: InsertRoute :exec
insert into routes (
	feed_id, feed_version_id, route_id, agency_id, route_short_name, route_long_name,
	route_desc, route_type, route_url, route_color, route_text_color, route_sort_order,
	continuous_pickup
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRouteParams struct {
	FeedID           int64          `json:"feed_id"`
	FeedVersionID    int64          `json:"feed_version_id"`
	RouteID          string         `json:"route_id"`
	AgencyID         sql.NullString `json:"agency_id"`
	RouteShortName   sql.NullString `json:"route_short_name"`
	RouteLongName    sql.NullString `json:"route_long_name"`
	RouteDesc        sql.NullString `json:"route_desc"`
	RouteType        sql.NullInt64  `json:"route_type"`
	RouteUrl         sql.NullString `json:"route_url"`
	RouteColor       sql.NullString `json:"route_color"`
	RouteTextColor   sql.NullString `json:"route_text_color"`
	RouteSortOrder   sql.NullString `json:"route_sort_order"`
	ContinuousPickup sql.NullString `json:"continuous_pickup"`
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) error {
	_, err := q.db.ExecContext(ctx, insertRoute,
		arg.FeedID,
		arg.FeedVersionID,
		arg.RouteID,
		arg.AgencyID,
		arg.RouteShortName,
		arg.RouteLongName,
		arg.RouteDesc,
		arg.RouteType,
		arg.RouteUrl,
		arg.RouteColor,
		arg.RouteTextColor,
		arg.RouteSortOrder,
		arg.ContinuousPickup,
	)
	return err
}

const insertShape = `-- name: InsertShape :exec
insert into shapes (
	feed_id, feed_version_id, shape_id, shape_pt_lat, shape_pt_lon, shape_pt_sequence
) values (?, ?, ?, ?, ?, ?)
`

type InsertShapeParams struct {
	FeedID          int64           `json:"feed_id"`
	FeedVersionID   int64           `json:"feed_version_id"`
	ShapeID         string          `json:"shape_id"`
	ShapePtLat      sql.NullFloat64 `json:"shape_pt_lat"`
	ShapePtLon      sql.NullFloat64 `json:"shape_pt_lon"`
	ShapePtSequence sql.NullInt64   `json:"shape_pt_sequence"`
}

func (q *Queries) InsertShape(ctx context.Context, arg InsertShapeParams) error {
	_, err := q.db.ExecContext(ctx, insertShape,
		arg.FeedID,
		arg.FeedVersionID,
		arg.ShapeID,
		arg.ShapePtLat,
		arg.ShapePtLon,
		arg.ShapePtSequence,
	)
	return err
}

const insertStop = `-- name: InsertStop :exec
insert into stops (
	feed_id, feed_version_id, stop_id, stop_code, stop_name, stop_desc, stop_lat,
	stop_lon, zone_id, stop_url, location_type, parent_station, stop_timezone,
	wheelchair_boarding, platform_code
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStopParams struct {
	FeedID             int64           `json:"feed_id"`
	FeedVersionID      int64           `json:"feed_version_id"`
	StopID             string          `json:"stop_id"`
	StopCode           sql.NullString  `json:"stop_code"`
	StopName           sql.NullString  `json:"stop_name"`
	StopDesc           sql.NullString  `json:"stop_desc"`
	StopLat            sql.NullFloat64 `json:"stop_lat"`
	StopLon            sql.NullFloat64 `json:"stop_lon"`
	ZoneID             sql.NullString  `json:"zone_id"`
	StopUrl            sql.NullString  `json:"stop_url"`
	LocationType       sql.NullInt64   `json:"location_type"`
	ParentStation      sql.NullString  `json:"parent_station"`
	StopTimezone       sql.NullString  `json:"stop_timezone"`
	WheelchairBoarding sql.NullString  `json:"wheelchair_boarding"`
	PlatformCode       sql.NullString  `json:"platform_code"`
}

func (q *Queries) InsertStop(ctx context.Context, arg InsertStopParams) error {
	_, err := q.db.ExecContext(ctx, insertStop,
		arg.FeedID,
		arg.FeedVersionID,
		arg.StopID,
		arg.StopCode,
		arg.StopName,
		arg.StopDesc,
		arg.StopLat,
		arg.StopLon,
		arg.ZoneID,
		arg.StopUrl,
		arg.LocationType,
		arg.ParentStation,
		arg.StopTimezone,
		arg.WheelchairBoarding,
		arg.PlatformCode,
	)
	return err
}

const insertStopTime = `-- name: InsertStopTime :exec
insert into stop_times (
	feed_id, feed_version_id, row_index, trip_id, arrival_time, departure_time,
	stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, continuous_pickup,
	continuous_drop_off, shape_dist_traveled, timepoint
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertStopTimeParams struct {
	FeedID            int64           `json:"feed_id"`
	FeedVersionID     int64           `json:"feed_version_id"`
	RowIndex          int64           `json:"row_index"`
	TripID            string          `json:"trip_id"`
	ArrivalTime       sql.NullString  `json:"arrival_time"`
	DepartureTime     sql.NullString  `json:"departure_time"`
	StopID            string          `json:"stop_id"`
	StopSequence      sql.NullInt64   `json:"stop_sequence"`
	StopHeadsign      sql.NullString  `json:"stop_headsign"`
	PickupType        sql.NullString  `json:"pickup_type"`
	DropOffType       sql.NullString  `json:"drop_off_type"`
	ContinuousPickup  sql.NullString  `json:"continuous_pickup"`
	ContinuousDropOff sql.NullString  `json:"continuous_drop_off"`
	ShapeDistTraveled sql.NullFloat64 `json:"shape_dist_traveled"`
	Timepoint         sql.NullString  `json:"timepoint"`
}

func (q *Queries) InsertStopTime(ctx context.Context, arg InsertStopTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertStopTime,
		arg.FeedID,
		arg.FeedVersionID,
		arg.RowIndex,
		arg.TripID,
		arg.ArrivalTime,
		arg.DepartureTime,
		arg.StopID,
		arg.StopSequence,
		arg.StopHeadsign,
		arg.PickupType,
		arg.DropOffType,
		arg.ContinuousPickup,
		arg.ContinuousDropOff,
		arg.ShapeDistTraveled,
		arg.Timepoint,
	)
	return err
}

const insertTransfer = `-- name: InsertTransfer :exec
insert into transfers (
	feed_id, feed_version_id, from_stop_id, to_stop_id, from_route_id, to_route_id,
	from_trip_id, to_trip_id, transfer_type, min_transfer_time
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTransferParams struct {
	FeedID          int64          `json:"feed_id"`
	FeedVersionID   int64          `json:"feed_version_id"`
	FromStopID      sql.NullString `json:"from_stop_id"`
	ToStopID        sql.NullString `json:"to_stop_id"`
	FromRouteID     sql.NullString `json:"from_route_id"`
	ToRouteID       sql.NullString `json:"to_route_id"`
	FromTripID      sql.NullString `json:"from_trip_id"`
	ToTripID        sql.NullString `json:"to_trip_id"`
	TransferType    sql.NullInt64  `json:"transfer_type"`
	MinTransferTime sql.NullInt64  `json:"min_transfer_time"`
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) error {
	_, err := q.db.ExecContext(ctx, insertTransfer,
		arg.FeedID,
		arg.FeedVersionID,
		arg.FromStopID,
		arg.ToStopID,
		arg.FromRouteID,
		arg.ToRouteID,
		arg.FromTripID,
		arg.ToTripID,
		arg.TransferType,
		arg.MinTransferTime,
	)
	return err
}

const insertTrip = `-- name: InsertTrip :exec
insert into trips (
	feed_id, feed_version_id, route_id, service_id, trip_id, trip_headsign,
	trip_short_name, direction_id, block_id, shape_id, wheelchair_accessible,
	bikes_allowed, cars_allowed
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTripParams struct {
	FeedID               int64          `json:"feed_id"`
	FeedVersionID        int64          `json:"feed_version_id"`
	RouteID              string         `json:"route_id"`
	ServiceID            string         `json:"service_id"`
	TripID               string         `json:"trip_id"`
	TripHeadsign         sql.NullString `json:"trip_headsign"`
	TripShortName        sql.NullString `json:"trip_short_name"`
	DirectionID          sql.NullInt64  `json:"direction_id"`
	BlockID              sql.NullString `json:"block_id"`
	ShapeID              sql.NullString `json:"shape_id"`
	WheelchairAccessible sql.NullString `json:"wheelchair_accessible"`
	BikesAllowed         sql.NullString `json:"bikes_allowed"`
	CarsAllowed          sql.NullString `json:"cars_allowed"`
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) error {
	_, err := q.db.ExecContext(ctx, insertTrip,
		arg.FeedID,
		arg.FeedVersionID,
		arg.RouteID,
		arg.ServiceID,
		arg.TripID,
		arg.TripHeadsign,
		arg.TripShortName,
		arg.DirectionID,
		arg.BlockID,
		arg.ShapeID,
		arg.WheelchairAccessible,
		arg.BikesAllowed,
		arg.CarsAllowed,
	)
	return err
}

const updateGTFSFileRowCount = `-- name: UpdateGTFSFileRowCount :exec
update gtfs_files set row_count = ? where id = ?
`

type UpdateGTFSFileRowCountParams struct {
	RowCount int64 `json:"row_count"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateGTFSFileRowCount(ctx context.Context, arg UpdateGTFSFileRowCountParams) error {
	_, err := q.db.ExecContext(ctx, updateGTFSFileRowCount, arg.RowCount, arg.ID)
	return err
}

const upsertFeed = `-- name: UpsertFeed :exec
insert into feeds (
	code, name, country_code, region, publisher_name, license_name, source_url, attribution_text
) values (?, ?, ?, ?, ?, ?, ?, ?)
on conflict(code) do update set
	name = excluded.name,
	country_code = excluded.country_code,
	region = excluded.region,
	publisher_name = excluded.publisher_name,
	license_name = excluded.license_name,
	source_url = excluded.source_url,
	attribution_text = excluded.attribution_text
`

type UpsertFeedParams struct {
	Code            string         `json:"code"`
	Name            string         `json:"name"`
	CountryCode     sql.NullString `json:"country_code"`
	Region          sql.NullString `json:"region"`
	PublisherName   sql.NullString `json:"publisher_name"`
	LicenseName     sql.NullString `json:"license_name"`
	SourceUrl       sql.NullString `json:"source_url"`
	AttributionText sql.NullString `json:"attribution_text"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeed,
		arg.Code,
		arg.Name,
		arg.CountryCode,
		arg.Region,
		arg.PublisherName,
		arg.LicenseName,
		arg.SourceUrl,
		arg.AttributionText,
	)
	return err
}
