// Generated by `go run ./tool/generate_feed_catalog`; do not edit by hand.
part of 'feed_catalog.dart';

const List<TransitFeed> kTransitFeeds = [
  TransitFeed(
    id: "jp-public-no-key",
    name: "Japan - available public feeds",
    description:
        "All no-key Japanese GTFS feeds currently known to the app, merged into one local routing network.",
    publisher: "Multiple public GTFS publishers",
    license: "Mixed open-data licences",
    sourceUrl: "Multiple GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of the Japanese feeds listed below. Licences vary by publisher; see each feed attribution.",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
    componentFeedIds: [
      "toei-train",
      "toei-bus",
      "kanazawa-flatbus",
      "kanazawa-hakusan-meguru",
      "kanazawa-tsubata-bus",
      "jbda-kaetsunou-kaetsunouippan",
      "jbda-nonoichicity-communitybus",
      "jbda-uchinadatown-communitybus",
      "jbda-komatsucity-blue",
      "jbda-komatsucity-orange",
      "jbda-komatsucity-kibagatasen",
      "jbda-chitetsu-chitetsubus",
      "jbda-chitetsu-chitetsushinaidensha",
      "jbda-manyosen-manyosen",
      "kobe-shiokaze",
      "kobe-satoyama",
      "himeji-ieshima",
      "takarazuka-runrunbus",
      "nishinomiya-sakurayamanami",
      "yamatokoriyama-kingyobus",
      "rinkan-koyasan",
      "jbda-akashicity-tacobustacobusmini",
      "jbda-kakogawacity-kakobuskakobusmini",
      "jbda-takasagocity-jotonbus",
      "jbda-nishinomiyacity-guruttonamaze",
      "jbda-nishinomiyacity-koyoen",
      "jbda-andotown-andocombus",
      "jbda-nabaricity-communitybus",
      "jbda-yamatotakadacity-communitybuskibougou",
      "jbda-higashiomicity-higasiohmisicommunitybus",
      "jbda-omihachimancity-akakonbus",
    ],
  ),
  TransitFeed(
    id: "tokyo-toei",
    name: "Tokyo Toei network",
    description:
        "Tokyo Metropolitan Bureau of Transportation subway, tram, liner, and municipal bus feeds merged into one network.",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl: "Multiple ODPT GTFS endpoints",
    localFileName: "",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
    componentFeedIds: ["toei-train", "toei-bus"],
  ),
  TransitFeed(
    id: "kanazawa-region",
    name: "Kanazawa region",
    description:
        "Kanazawa, Ishikawa, and nearby Hokuriku public bus and tram feeds merged into one regional network.",
    publisher: "Multiple Hokuriku public-data publishers",
    license: "Mixed open-data licences",
    sourceUrl: "Multiple GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of Kanazawa, Ishikawa, and nearby Hokuriku public GTFS feeds; see each feed attribution below.",
    centerLatitude: 36.5608,
    centerLongitude: 136.6566,
    componentFeedIds: [
      "kanazawa-flatbus",
      "kanazawa-hakusan-meguru",
      "kanazawa-tsubata-bus",
      "jbda-kaetsunou-kaetsunouippan",
      "jbda-nonoichicity-communitybus",
      "jbda-uchinadatown-communitybus",
      "jbda-komatsucity-blue",
      "jbda-komatsucity-orange",
      "jbda-komatsucity-kibagatasen",
      "jbda-chitetsu-chitetsubus",
      "jbda-chitetsu-chitetsushinaidensha",
      "jbda-manyosen-manyosen",
    ],
  ),
  TransitFeed(
    id: "kansai-public-no-key",
    name: "Kansai - available public feeds",
    description:
        "Public no-key Hyogo, Nara, Shiga, and Wakayama feeds. This does not include major JR or private rail.",
    publisher: "Multiple public GTFS publishers",
    license: "Mixed open-data licences",
    sourceUrl: "Multiple GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of the Kansai-area no-key public feeds listed below. Major rail is not included.",
    centerLatitude: 34.6937,
    centerLongitude: 135.5023,
    componentFeedIds: [
      "kobe-shiokaze",
      "kobe-satoyama",
      "himeji-ieshima",
      "takarazuka-runrunbus",
      "nishinomiya-sakurayamanami",
      "yamatokoriyama-kingyobus",
      "rinkan-koyasan",
      "jbda-akashicity-tacobustacobusmini",
      "jbda-kakogawacity-kakobuskakobusmini",
      "jbda-takasagocity-jotonbus",
      "jbda-nishinomiyacity-guruttonamaze",
      "jbda-nishinomiyacity-koyoen",
      "jbda-andotown-andocombus",
      "jbda-nabaricity-communitybus",
      "jbda-yamatotakadacity-communitybuskibougou",
      "jbda-higashiomicity-higasiohmisicommunitybus",
      "jbda-omihachimancity-akakonbus",
    ],
  ),
  TransitFeed(
    id: "himeji-ieshima",
    name: "Himeji Ieshima Routes",
    description: "Himeji Ieshima / Boze / Yukihiko routes, via gtfs-data.jp",
    publisher: "Himeji City (姫路市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/himejicity/feeds/ieshima-boze-yukihiko/files/feed.zip?rid=current",
    localFileName: "himeji-ieshima.zip",
    attribution: "Transit data © Himeji City (姫路市), CC-BY-2.1-JP.",
    centerLatitude: 34.8151,
    centerLongitude: 134.6854,
  ),
  TransitFeed(
    id: "jbda-akashicity-tacobustacobusmini",
    name: "Akashi Taco Bus",
    description:
        "Akashi Taco Bus and Taco Bus Mini, mirrored by Mobility Database.",
    publisher: "明石市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-akashicity-tacobustacobusmini/latest.zip",
    localFileName: "jbda-akashicity-tacobustacobusmini.zip",
    attribution:
        "Transit data © 明石市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 34.68995,
    centerLongitude: 134.923916,
  ),
  TransitFeed(
    id: "jbda-andotown-andocombus",
    name: "Ando Community Bus",
    description: "Ando community bus, mirrored by Mobility Database.",
    publisher: "安堵町",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-andotown-andocombus/latest.zip",
    localFileName: "jbda-andotown-andocombus.zip",
    attribution:
        "Transit data © 安堵町, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 34.60031,
    centerLongitude: 135.761048,
  ),
  TransitFeed(
    id: "jbda-chitetsu-chitetsubus",
    name: "Toyama Chitetsu Bus",
    description: "Toyama Chitetsu bus network, mirrored by Mobility Database.",
    publisher: "富山地方鉄道",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-chitetsu-chitetsubus/latest.zip",
    localFileName: "jbda-chitetsu-chitetsubus.zip",
    attribution:
        "Transit data © 富山地方鉄道, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.733815,
    centerLongitude: 137.24869,
  ),
  TransitFeed(
    id: "jbda-chitetsu-chitetsushinaidensha",
    name: "Toyama Chitetsu City Tram",
    description:
        "Toyama Chitetsu city tram network, mirrored by Mobility Database.",
    publisher: "富山地方鉄道",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-chitetsu-chitetsushinaidensha/latest.zip",
    localFileName: "jbda-chitetsu-chitetsushinaidensha.zip",
    attribution:
        "Transit data © 富山地方鉄道, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.715942,
    centerLongitude: 137.212628,
  ),
  TransitFeed(
    id: "jbda-higashiomicity-higasiohmisicommunitybus",
    name: "Higashiomi Chokotto Bus",
    description: "Higashiomi Chokotto Bus, mirrored by Mobility Database.",
    publisher: "東近江市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-higashiomicity-higasiohmisicommunitybus/latest.zip",
    localFileName: "jbda-higashiomicity-higasiohmisicommunitybus.zip",
    attribution:
        "Transit data © 東近江市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 35.129049,
    centerLongitude: 136.248841,
  ),
  TransitFeed(
    id: "jbda-kaetsunou-kaetsunouippan",
    name: "Kaetsunou Bus",
    description:
        "Kaetsunou general route bus network around Kanazawa, mirrored by Mobility Database.",
    publisher: "加越能バス",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-kaetsunou-kaetsunouippan/latest.zip",
    localFileName: "jbda-kaetsunou-kaetsunouippan.zip",
    attribution:
        "Transit data © 加越能バス, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.740017,
    centerLongitude: 136.9026,
  ),
  TransitFeed(
    id: "jbda-kakogawacity-kakobuskakobusmini",
    name: "Kakogawa Kako Bus",
    description:
        "Kakogawa Kako Bus and Kako Bus Mini, mirrored by Mobility Database.",
    publisher: "加古川市",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-kakogawacity-kakobuskakobusmini/latest.zip",
    localFileName: "jbda-kakogawacity-kakobuskakobusmini.zip",
    attribution:
        "Transit data © 加古川市, CC-BY-2.1-JP; mirrored by Mobility Database.",
    centerLatitude: 34.779365,
    centerLongitude: 134.845272,
  ),
  TransitFeed(
    id: "jbda-komatsucity-blue",
    name: "Komatsu North Loop",
    description: "Komatsu city north loop bus, mirrored by Mobility Database.",
    publisher: "小松市",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-komatsucity-blue/latest.zip",
    localFileName: "jbda-komatsucity-blue.zip",
    attribution: "Transit data © 小松市, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.414092,
    centerLongitude: 136.459254,
  ),
  TransitFeed(
    id: "jbda-komatsucity-kibagatasen",
    name: "Komatsu Kibagata Line",
    description: "Komatsu Kibagata bus line, mirrored by Mobility Database.",
    publisher: "小松市",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-komatsucity-kibagatasen/latest.zip",
    localFileName: "jbda-komatsucity-kibagatasen.zip",
    attribution: "Transit data © 小松市, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.373056,
    centerLongitude: 136.458775,
  ),
  TransitFeed(
    id: "jbda-komatsucity-orange",
    name: "Komatsu South Loop",
    description: "Komatsu city south loop bus, mirrored by Mobility Database.",
    publisher: "小松市",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-komatsucity-orange/latest.zip",
    localFileName: "jbda-komatsucity-orange.zip",
    attribution: "Transit data © 小松市, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.395266,
    centerLongitude: 136.470707,
  ),
  TransitFeed(
    id: "jbda-manyosen-manyosen",
    name: "Manyosen Tram",
    description: "Manyosen tram network, mirrored by Mobility Database.",
    publisher: "万葉線",
    license: "CC0-1.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-manyosen-manyosen/latest.zip",
    localFileName: "jbda-manyosen-manyosen.zip",
    attribution: "Transit data © 万葉線, CC0-1.0; mirrored by Mobility Database.",
    centerLatitude: 36.765312,
    centerLongitude: 137.06241,
  ),
  TransitFeed(
    id: "jbda-nabaricity-communitybus",
    name: "Nabari Community Bus",
    description: "Nabari community bus, mirrored by Mobility Database.",
    publisher: "名張市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-nabaricity-communitybus/latest.zip",
    localFileName: "jbda-nabaricity-communitybus.zip",
    attribution:
        "Transit data © 名張市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 34.622912,
    centerLongitude: 136.115424,
  ),
  TransitFeed(
    id: "jbda-nishinomiyacity-guruttonamaze",
    name: "Nishinomiya Gurutto Namaze",
    description:
        "Nishinomiya Gurutto Namaze community bus, mirrored by Mobility Database.",
    publisher: "西宮市",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-nishinomiyacity-guruttonamaze/latest.zip",
    localFileName: "jbda-nishinomiyacity-guruttonamaze.zip",
    attribution:
        "Transit data © 西宮市, CC-BY-2.1-JP; mirrored by Mobility Database.",
    centerLatitude: 34.819407,
    centerLongitude: 135.328093,
  ),
  TransitFeed(
    id: "jbda-nishinomiyacity-koyoen",
    name: "Nishinomiya Koyoen Bus",
    description:
        "Nishinomiya Koyoen community bus, mirrored by Mobility Database.",
    publisher: "西宮市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-nishinomiyacity-koyoen/latest.zip",
    localFileName: "jbda-nishinomiyacity-koyoen.zip",
    attribution:
        "Transit data © 西宮市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 34.766085,
    centerLongitude: 135.327792,
  ),
  TransitFeed(
    id: "jbda-nonoichicity-communitybus",
    name: "Nonoichi Community Bus",
    description:
        "Nonoichi community bus network, mirrored by Mobility Database.",
    publisher: "野々市市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-nonoichicity-communitybus/latest.zip",
    localFileName: "jbda-nonoichicity-communitybus.zip",
    attribution:
        "Transit data © 野々市市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 36.524932,
    centerLongitude: 136.59714,
  ),
  TransitFeed(
    id: "jbda-omihachimancity-akakonbus",
    name: "Omihachiman Akakon Bus",
    description: "Omihachiman Akakon Bus, mirrored by Mobility Database.",
    publisher: "近江八幡市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-omihachimancity-akakonbus/latest.zip",
    localFileName: "jbda-omihachimancity-akakonbus.zip",
    attribution:
        "Transit data © 近江八幡市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 35.135921,
    centerLongitude: 136.096512,
  ),
  TransitFeed(
    id: "jbda-takasagocity-jotonbus",
    name: "Takasago Joton Bus",
    description: "Takasago Joton Bus, mirrored by Mobility Database.",
    publisher: "高砂市",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-takasagocity-jotonbus/latest.zip",
    localFileName: "jbda-takasagocity-jotonbus.zip",
    attribution:
        "Transit data © 高砂市, CC-BY-2.1-JP; mirrored by Mobility Database.",
    centerLatitude: 34.77986,
    centerLongitude: 134.792922,
  ),
  TransitFeed(
    id: "jbda-uchinadatown-communitybus",
    name: "Uchinada Community Bus",
    description:
        "Uchinada community bus network, mirrored by Mobility Database.",
    publisher: "内灘町",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-uchinadatown-communitybus/latest.zip",
    localFileName: "jbda-uchinadatown-communitybus.zip",
    attribution:
        "Transit data © 内灘町, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 36.660712,
    centerLongitude: 136.65223,
  ),
  TransitFeed(
    id: "jbda-yamatotakadacity-communitybuskibougou",
    name: "Yamatotakada Kibou Bus",
    description:
        "Yamatotakada Kibou community bus, mirrored by Mobility Database.",
    publisher: "大和高田市",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://files.mobilitydatabase.org/jbda-yamatotakadacity-communitybuskibougou/latest.zip",
    localFileName: "jbda-yamatotakadacity-communitybuskibougou.zip",
    attribution:
        "Transit data © 大和高田市, CC-BY-4.0; mirrored by Mobility Database.",
    centerLatitude: 34.502817,
    centerLongitude: 135.742643,
  ),
  TransitFeed(
    id: "kanazawa-flatbus",
    name: "Kanazawa Flat Bus",
    description:
        "Kanazawa city bus network, published as GTFS on the city open-data catalog.",
    publisher: "Kanazawa City, Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/1196beb4-f9f9-463c-9723-5b38d8127425/resource/9636cac5-1449-4656-893b-ec98d834eb23/download/flatbus20260401.zip",
    localFileName: "flatbus20260401.zip",
    attribution:
        "Transit data © Kanazawa City (Kanazawa-ken Jichitai), CC-BY 4.0.",
    centerLatitude: 36.5608,
    centerLongitude: 136.6566,
  ),
  TransitFeed(
    id: "kanazawa-hakusan-meguru",
    name: "Hakusan Meguru",
    description:
        "Hakusan City Community Bus (\"Meguru\") network GTFS from the municipal open-data portal.",
    publisher: "Hakusan City, Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/89d93f28-38b4-4971-9988-2ff2d3227f56/resource/50049b19-fe9f-4ca1-9ea9-9d0a24141644/download/172103_bus.zip",
    localFileName: "172103_bus.zip",
    attribution: "Transit data © Hakusan City (白山市), CC-BY 4.0.",
    centerLatitude: 36.2581,
    centerLongitude: 136.629,
  ),
  TransitFeed(
    id: "kanazawa-tsubata-bus",
    name: "Tsubata Town Bus",
    description: "Tsubata Town bus routes on the GSF/GTFS-JP package.",
    publisher: "Tsubata Town (Tsubata-chō), Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/8cd7f0dc-aab0-4bf4-a09d-c1d79faf4512/resource/9565f9b7-3bf7-4937-bee5-789d2aa4bf8a/download/gtfs-jp_tsubata.zip",
    localFileName: "gtfs-jp_tsubata.zip",
    attribution:
        "Transit data © Tsubata Town / Kanazawa public transport data, CC-BY 4.0.",
    centerLatitude: 36.7381,
    centerLongitude: 136.5596,
  ),
  TransitFeed(
    id: "kobe-satoyama",
    name: "Kobe Satoyama Bus",
    description: "Kobe Satoyama community bus, via gtfs-data.jp",
    publisher: "Kobe City (神戸市)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/kobecity/feeds/kobe-satoyama/files/feed.zip?rid=current",
    localFileName: "kobe-satoyama.zip",
    attribution: "Transit data © Kobe City (神戸市), CC-BY-4.0.",
    centerLatitude: 34.6901,
    centerLongitude: 135.1955,
  ),
  TransitFeed(
    id: "kobe-shiokaze",
    name: "Kobe Shiokaze Bus",
    description: "Kobe Shiokaze community bus, via gtfs-data.jp",
    publisher: "Kobe City (神戸市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/kobecity/feeds/kobe-shiokaze/files/feed.zip?rid=current",
    localFileName: "kobe-shiokaze.zip",
    attribution: "Transit data © Kobe City (神戸市), CC-BY-2.1-JP.",
    centerLatitude: 34.6901,
    centerLongitude: 135.1955,
  ),
  TransitFeed(
    id: "nishinomiya-sakurayamanami",
    name: "Nishinomiya Sakurayamanami Bus",
    description: "Nishinomiya Sakurayamanami community bus, via gtfs-data.jp",
    publisher: "Nishinomiya City (西宮市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/nishinomiyacity/feeds/sakurayamanami/files/feed.zip?rid=current",
    localFileName: "nishinomiya-sakurayamanami.zip",
    attribution: "Transit data © Nishinomiya City (西宮市), CC-BY-2.1-JP.",
    centerLatitude: 34.7376,
    centerLongitude: 135.3416,
  ),
  TransitFeed(
    id: "rinkan-koyasan",
    name: "Nankai Rinkan Koyasan Bus",
    description: "Mt. Koya / Koyasan bus network, via gtfs-data.jp",
    publisher: "Nankai Rinkan Bus (南海りんかんバス)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/rinkan/feeds/koyasan/files/feed.zip?rid=current",
    localFileName: "rinkan-koyasan.zip",
    attribution: "Transit data © Nankai Rinkan Bus (南海りんかんバス), CC-BY-4.0.",
    centerLatitude: 34.212,
    centerLongitude: 135.5867,
  ),
  TransitFeed(
    id: "takarazuka-runrunbus",
    name: "Takarazuka Runrun Bus",
    description: "Takarazuka runrun community bus, via gtfs-data.jp",
    publisher: "Takarazuka City (宝塚市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/takarazukacity/feeds/runrunbus/files/feed.zip?rid=current",
    localFileName: "takarazuka-runrunbus.zip",
    attribution: "Transit data © Takarazuka City (宝塚市), CC-BY-2.1-JP.",
    centerLatitude: 34.8114,
    centerLongitude: 135.3407,
  ),
  TransitFeed(
    id: "toei-bus",
    name: "Tokyo Toei Bus",
    description:
        "Tokyo Metropolitan Bureau of Transportation municipal bus routes.",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api-public.odpt.org/api/v4/files/Toei/data/ToeiBus-GTFS.zip",
    localFileName: "ToeiBus-GTFS.zip",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
  ),
  TransitFeed(
    id: "toei-train",
    name: "Tokyo Toei Subway",
    description: "Toei subway lines (浅草線, 三田線, 新宿線, 大江戸線, 日暮里舎人ライナー, 都電荒川線).",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api-public.odpt.org/api/v4/files/Toei/data/Toei-Train-GTFS.zip",
    localFileName: "Toei-Train-GTFS.zip",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    bundledAssetPath: "assets/sample_toei_train/Toei-Train-GTFS.zip",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
  ),
  TransitFeed(
    id: "yamatokoriyama-kingyobus",
    name: "Yamatokoriyama Kingyo Bus",
    description: "Yamatokoriyama Kingyo community bus, via gtfs-data.jp",
    publisher: "Yamatokoriyama City (大和郡山市)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/yamatokoriyamacity/feeds/kingyobus/files/feed.zip?rid=current",
    localFileName: "yamatokoriyama-kingyobus.zip",
    attribution: "Transit data © Yamatokoriyama City (大和郡山市), CC-BY-4.0.",
    centerLatitude: 34.649,
    centerLongitude: 135.7828,
  ),
];
