// Generated by `go run ./tool/generate_feed_catalog`; do not edit by hand.
part of 'feed_catalog.dart';

const List<TransitFeed> kTransitFeeds = [
  TransitFeed(
    id: "jp-public-no-key",
    name: "Japan - available public feeds",
    description:
        "All no-key Japanese GTFS feeds currently known to the app, merged into one local routing network.",
    publisher: "Multiple public GTFS publishers",
    license: "Mixed open-data licences",
    sourceUrl: "Multiple GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of the Japanese feeds listed below. Licences vary by publisher; see each feed attribution.",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
    componentFeedIds: [
      "toei-train",
      "toei-bus",
      "kanazawa-flatbus",
      "kanazawa-hakusan-meguru",
      "kanazawa-tsubata-bus",
      "kobe-shiokaze",
      "kobe-satoyama",
      "himeji-ieshima",
      "takarazuka-runrunbus",
      "nishinomiya-sakurayamanami",
      "yamatokoriyama-kingyobus",
      "rinkan-koyasan",
    ],
  ),
  TransitFeed(
    id: "tokyo-toei",
    name: "Tokyo Toei network",
    description:
        "Tokyo Metropolitan Bureau of Transportation subway, tram, liner, and municipal bus feeds merged into one network.",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl: "Multiple ODPT GTFS endpoints",
    localFileName: "",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
    componentFeedIds: ["toei-train", "toei-bus"],
  ),
  TransitFeed(
    id: "kanazawa-region",
    name: "Kanazawa region",
    description:
        "Kanazawa and nearby Hakusan/Tsubata public bus feeds merged into one regional network.",
    publisher: "Multiple Ishikawa public-data publishers",
    license: "CC-BY-4.0",
    sourceUrl: "Multiple municipal GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of Kanazawa, Hakusan, and Tsubata public GTFS feeds; see each feed attribution below.",
    centerLatitude: 36.5608,
    centerLongitude: 136.6566,
    componentFeedIds: [
      "kanazawa-flatbus",
      "kanazawa-hakusan-meguru",
      "kanazawa-tsubata-bus",
    ],
  ),
  TransitFeed(
    id: "kansai-public-no-key",
    name: "Kansai - available public feeds",
    description:
        "Small public no-key Hyogo, Nara, and Wakayama feeds. This does not include major JR or private rail.",
    publisher: "Multiple public GTFS publishers",
    license: "Mixed open-data licences",
    sourceUrl: "Multiple GTFS endpoints",
    localFileName: "",
    attribution:
        "Merged network of the Kansai-area no-key public feeds listed below. Major rail is not included.",
    centerLatitude: 34.6937,
    centerLongitude: 135.5023,
    componentFeedIds: [
      "kobe-shiokaze",
      "kobe-satoyama",
      "himeji-ieshima",
      "takarazuka-runrunbus",
      "nishinomiya-sakurayamanami",
      "yamatokoriyama-kingyobus",
      "rinkan-koyasan",
    ],
  ),
  TransitFeed(
    id: "himeji-ieshima",
    name: "Himeji Ieshima Routes",
    description: "Himeji Ieshima / Boze / Yukihiko routes, via gtfs-data.jp",
    publisher: "Himeji City (姫路市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/himejicity/feeds/ieshima-boze-yukihiko/files/feed.zip?rid=current",
    localFileName: "himeji-ieshima.zip",
    attribution: "Transit data © Himeji City (姫路市), CC-BY-2.1-JP.",
    centerLatitude: 34.8151,
    centerLongitude: 134.6854,
  ),
  TransitFeed(
    id: "kanazawa-flatbus",
    name: "Kanazawa Flat Bus",
    description:
        "Kanazawa city bus network, published as GTFS on the city open-data catalog.",
    publisher: "Kanazawa City, Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/1196beb4-f9f9-463c-9723-5b38d8127425/resource/9636cac5-1449-4656-893b-ec98d834eb23/download/flatbus20260401.zip",
    localFileName: "flatbus20260401.zip",
    attribution:
        "Transit data © Kanazawa City (Kanazawa-ken Jichitai), CC-BY 4.0.",
    centerLatitude: 36.5608,
    centerLongitude: 136.6566,
  ),
  TransitFeed(
    id: "kanazawa-hakusan-meguru",
    name: "Hakusan Meguru",
    description:
        "Hakusan City Community Bus (\"Meguru\") network GTFS from the municipal open-data portal.",
    publisher: "Hakusan City, Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/89d93f28-38b4-4971-9988-2ff2d3227f56/resource/50049b19-fe9f-4ca1-9ea9-9d0a24141644/download/172103_bus.zip",
    localFileName: "172103_bus.zip",
    attribution: "Transit data © Hakusan City (白山市), CC-BY 4.0.",
    centerLatitude: 36.2581,
    centerLongitude: 136.629,
  ),
  TransitFeed(
    id: "kanazawa-tsubata-bus",
    name: "Tsubata Town Bus",
    description: "Tsubata Town bus routes on the GSF/GTFS-JP package.",
    publisher: "Tsubata Town (Tsubata-chō), Ishikawa",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://catalog-data.city.kanazawa.ishikawa.jp/dataset/8cd7f0dc-aab0-4bf4-a09d-c1d79faf4512/resource/9565f9b7-3bf7-4937-bee5-789d2aa4bf8a/download/gtfs-jp_tsubata.zip",
    localFileName: "gtfs-jp_tsubata.zip",
    attribution:
        "Transit data © Tsubata Town / Kanazawa public transport data, CC-BY 4.0.",
    centerLatitude: 36.7381,
    centerLongitude: 136.5596,
  ),
  TransitFeed(
    id: "kobe-satoyama",
    name: "Kobe Satoyama Bus",
    description: "Kobe Satoyama community bus, via gtfs-data.jp",
    publisher: "Kobe City (神戸市)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/kobecity/feeds/kobe-satoyama/files/feed.zip?rid=current",
    localFileName: "kobe-satoyama.zip",
    attribution: "Transit data © Kobe City (神戸市), CC-BY-4.0.",
    centerLatitude: 34.6901,
    centerLongitude: 135.1955,
  ),
  TransitFeed(
    id: "kobe-shiokaze",
    name: "Kobe Shiokaze Bus",
    description: "Kobe Shiokaze community bus, via gtfs-data.jp",
    publisher: "Kobe City (神戸市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/kobecity/feeds/kobe-shiokaze/files/feed.zip?rid=current",
    localFileName: "kobe-shiokaze.zip",
    attribution: "Transit data © Kobe City (神戸市), CC-BY-2.1-JP.",
    centerLatitude: 34.6901,
    centerLongitude: 135.1955,
  ),
  TransitFeed(
    id: "nishinomiya-sakurayamanami",
    name: "Nishinomiya Sakurayamanami Bus",
    description: "Nishinomiya Sakurayamanami community bus, via gtfs-data.jp",
    publisher: "Nishinomiya City (西宮市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/nishinomiyacity/feeds/sakurayamanami/files/feed.zip?rid=current",
    localFileName: "nishinomiya-sakurayamanami.zip",
    attribution: "Transit data © Nishinomiya City (西宮市), CC-BY-2.1-JP.",
    centerLatitude: 34.7376,
    centerLongitude: 135.3416,
  ),
  TransitFeed(
    id: "rinkan-koyasan",
    name: "Nankai Rinkan Koyasan Bus",
    description: "Mt. Koya / Koyasan bus network, via gtfs-data.jp",
    publisher: "Nankai Rinkan Bus (南海りんかんバス)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/rinkan/feeds/koyasan/files/feed.zip?rid=current",
    localFileName: "rinkan-koyasan.zip",
    attribution: "Transit data © Nankai Rinkan Bus (南海りんかんバス), CC-BY-4.0.",
    centerLatitude: 34.212,
    centerLongitude: 135.5867,
  ),
  TransitFeed(
    id: "takarazuka-runrunbus",
    name: "Takarazuka Runrun Bus",
    description: "Takarazuka runrun community bus, via gtfs-data.jp",
    publisher: "Takarazuka City (宝塚市)",
    license: "CC-BY-2.1-JP",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/takarazukacity/feeds/runrunbus/files/feed.zip?rid=current",
    localFileName: "takarazuka-runrunbus.zip",
    attribution: "Transit data © Takarazuka City (宝塚市), CC-BY-2.1-JP.",
    centerLatitude: 34.8114,
    centerLongitude: 135.3407,
  ),
  TransitFeed(
    id: "toei-bus",
    name: "Tokyo Toei Bus",
    description:
        "Tokyo Metropolitan Bureau of Transportation municipal bus routes.",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api-public.odpt.org/api/v4/files/Toei/data/ToeiBus-GTFS.zip",
    localFileName: "ToeiBus-GTFS.zip",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
  ),
  TransitFeed(
    id: "toei-train",
    name: "Tokyo Toei Subway",
    description: "Toei subway lines (浅草線, 三田線, 新宿線, 大江戸線, 日暮里舎人ライナー, 都電荒川線).",
    publisher: "Tokyo Metropolitan Bureau of Transportation (東京都交通局)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api-public.odpt.org/api/v4/files/Toei/data/Toei-Train-GTFS.zip",
    localFileName: "Toei-Train-GTFS.zip",
    attribution:
        "Transit data © 東京都交通局 (Tokyo Metropolitan Bureau of Transportation), CC-BY 4.0, via the Public Transportation Open Data Center (ODPT).",
    bundledAssetPath: "assets/sample_toei_train/Toei-Train-GTFS.zip",
    defaultDepartureHour: 8,
    centerLatitude: 35.681236,
    centerLongitude: 139.767125,
  ),
  TransitFeed(
    id: "yamatokoriyama-kingyobus",
    name: "Yamatokoriyama Kingyo Bus",
    description: "Yamatokoriyama Kingyo community bus, via gtfs-data.jp",
    publisher: "Yamatokoriyama City (大和郡山市)",
    license: "CC-BY-4.0",
    sourceUrl:
        "https://api.gtfs-data.jp/v2/organizations/yamatokoriyamacity/feeds/kingyobus/files/feed.zip?rid=current",
    localFileName: "yamatokoriyama-kingyobus.zip",
    attribution: "Transit data © Yamatokoriyama City (大和郡山市), CC-BY-4.0.",
    centerLatitude: 34.649,
    centerLongitude: 135.7828,
  ),
];
